### PR TITLE
Images Mirroring and other control for Kinect 

### PR DESCRIPTION
**Pull request by KHeresy**
I tried to make the suppot for mirroring on Kinect Device.
It works fine on my computer, hope someone could test this.

I also add some property to enable the control of Kinect: 
KINECT_DEVICE_PROPERTY_CAMERA_ELEVATION
KINECT_DEVICE_PROPERTY_ACCELEROMETER
KINECT_DEPTH_PROPERTY_NEAR_MODE

If it wroks, I hope this could be merged into next release of OpenNI.

### CODE REVIEW

**Comment by KHeresy** [comment]
See more detail in http://community.openni.org/openni/topics/enhanced_version_of_kinect_dll

**Comment by joshuanapoli** [comment]
Thanks for this patch! The KINECT_DEVICE_PROPERTY_ACCELEROMETER property is useful to me and I tested that it works properly. The patch is useful to me and I hope that it will be merged into OpenNI2.

**Comment by Reelsun** [comment]
+1

**Comment by tomoto** [comment]
I am working with Eddie to add the mirror mode support. Please see #32 for more details.

Regarding the extended parameters you are proposing, I think it is also useful but would rather not mix in one pull request. I will work on it separately.

Cheers,

**Comment by KHeresy** [comment]
Thanks for enchance the code.
Hope these feature may be better.

**Comment by eddiecohen** [comment]
Done with tomoto's implementation (8fea30e1cad144ea1e2fe03410bbed95a3a79638).

Thanks!

**Comment by tomoto** [comment]
Eddie, thank you very much for getting it done so quickly!

**Pull request closed without merging**
